### ISSUE TITLE
Make the homepage more mobile friendly

### ISSUE THREAD

**Issue by dannyparsons** [IDEMSInternational/virtual-maths-camp-gh-pages#7]
Some of the website pages already look ok on a mobile device. I think the set of images on the homepage is making it look less sensible on mobile devices. Possibly adjusting how the images are displayed could fix this?

![image](https://user-images.githubusercontent.com/11214914/88279852-a3ba7a00-ccdc-11ea-9d87-a211931a91ef.png)

**Comment by hileamlakB** [comment]
I would like to help here

**Comment by dannyparsons** [comment]
That would be great! I think the homepage issue is resolved now that the photos have been resized but the first thing you could do if have a look at all the pages on a mobile device and see if there are any issue or anything that could improve the display on a small screen.

**Comment by hileamlakB** [comment]
I can work on making a dropdown nav bar for the mobile version

**Comment by hileamlakB** [comment]
I also have some design ideas. I will show you when I finish it if you are interested.

**Comment by dannyparsons** [comment]
That sounds great. Please also share with @smborio who is managing the website.

**Comment by hileamlakB** [comment]
![Desktop - 1 (1)](https://user-images.githubusercontent.com/68893442/89637570-09009480-d8b3-11ea-9db4-04a4a108f9f8.png)
Here is the design  I have in mind. You may need to zoom in to see it since it isn't proportional. ere is a zoomed in version. 
![image](https://user-images.githubusercontent.com/68893442/89638227-1cf8c600-d8b4-11ea-87f4-456370b382b4.png)

If you like this design I will quickly finish up the design for the mobile version and the rest of the pages and will get to work quickly. Also, if there are improvements I can add I would like to hear them. And if you think the current version is good, dont hestate to just say it to my face.

**Comment by hileamlakB** [comment]
@smborio didn't answer my email yesterday. Let me know what you tink, so that I can get started either on the new look or the nav bar.

**Comment by hileamlakB** [comment]
A preview,(it  is just an  image so don't expect it to be responsive)
https://www.figma.com/file/lJkUWHe8tJUE957T3ZDX7B/Virtual-Math-camp?node-id=0%3A1

**Comment by dannyparsons** [comment]
Thanks @hileamlakB! I think this looks great. It would be good to keep the image carousel as well if possible. 
Let's wait for a response from Santiago before confirming though.

**Comment by hileamlakB** [comment]
Yes, I will keep the carousel, the one represented as an image in the design will be a carousel.

**Comment by hileamlakB** [comment]
Can you please get to @smborio.

**Comment by smborio** [comment]
Hi @hileamlakB Sorry for my late response! The design ideas look great and we definitely have to work on the design aspect of the site. I'd be more than happy to include you on the development team. Just for a bit of context, this is a placeholder website which we will be migrating to a new version using angular. Perhaps we can have a call at some point soon to go over things. I'll send you an email directly to see what is sensible.

Many thanks!
